# Server configuration
server:
  # Server address to bind to
  address: 0.0.0.0
  # Server port to bind to
  port: 3000
  # Update interval to reload the config file. (ms, 0 to disable) NOTE: This will not update the server binding info.
  configUpdateInterval: 10000
  # Update interval to get data from Influx and FNE REST API to send to clients. (ms)
  updateInterval: 2000
  # Skip affiliations from ignored peers. If true, affiliations from ignored peers are not sent to clients.
  skipAffiliationsFromIgnoredPeers: true
  # Global ignored peers. These peers are removed upon receiving data from FNE and will never be sent anywhere.
  ignoredPeers: []

# FNE REST API configuration
fne:
  # FNE REST API address
  address: 127.0.0.1
  # FNE REST API port
  port: 9990
  # FNE REST API password
  password: "PASSWORD"

# FNE InfluxDB configuration
influxdb:
  # InfluxDB URL
  url: "http://127.0.0.1:8086"
  # InfluxDB token
  token: "PASSWORD"
  # InfluxDB organization
  org: "dvm"
  # InfluxDB bucket
  bucket: "dvm"